import os

# ATLAS
ATLAS_BASE_URL = os.environ.get("ATLAS_BASE_URL")
ATLAS_API_ENDPOINT = "/api/atlas"
ENTITY_API_ENDPOINT = "/v2/entity"

# JSON KEYS
TYPE_NAME = "typeName"
ENTITY = "entity"
ATTRIBUTES = "attributes"
QUALIFIED_NAME = "qualifiedName"
NAME = "name"
GUID = "guid"
TRIM = "trim"
DATA = "data"
START_TIME = "starttime"
END_TIME = "endtime"
ID = "id"
UNIQUE_ATTRIBUTES = "uniqueAttributes"
RELATIONSHIP_ATTRIBUTES = "relationshipAttributes"
INPUTS = "inputs"
OUTPUTS = "outputs"
CREATE_TABLE = "CREATE TABLE"
DROP_TABLE = "DROP TABLE"
CREATE_DATABASE = "CREATE DATABASE"
DROP_DATABASE = "DROP DATABASE"
ALTER_TABLE = "ALTER TABLE"
INSTANCE = "instance"
RELATIONSHIP_TYPE = "relationshipType"
TYPE = "type"
USER = "user"
ENTITIES = "entities"
VERSION = "version"
VERSION_PARTS = "versionParts"
